// Code generated by protoc-gen-go. DO NOT EDIT.
// source: verified.proto

package waproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifiedName struct {
	VerifiedOne          *VerifiedName_VerifiedOne `protobuf:"bytes,1,opt,name=verifiedOne" json:"verifiedOne,omitempty"`
	VerifiedTow          []byte                    `protobuf:"bytes,2,opt,name=verifiedTow" json:"verifiedTow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *VerifiedName) Reset()         { *m = VerifiedName{} }
func (m *VerifiedName) String() string { return proto.CompactTextString(m) }
func (*VerifiedName) ProtoMessage()    {}
func (*VerifiedName) Descriptor() ([]byte, []int) {
	return fileDescriptor_39cdc64788007a21, []int{0}
}

func (m *VerifiedName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifiedName.Unmarshal(m, b)
}
func (m *VerifiedName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifiedName.Marshal(b, m, deterministic)
}
func (m *VerifiedName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifiedName.Merge(m, src)
}
func (m *VerifiedName) XXX_Size() int {
	return xxx_messageInfo_VerifiedName.Size(m)
}
func (m *VerifiedName) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifiedName.DiscardUnknown(m)
}

var xxx_messageInfo_VerifiedName proto.InternalMessageInfo

func (m *VerifiedName) GetVerifiedOne() *VerifiedName_VerifiedOne {
	if m != nil {
		return m.VerifiedOne
	}
	return nil
}

func (m *VerifiedName) GetVerifiedTow() []byte {
	if m != nil {
		return m.VerifiedTow
	}
	return nil
}

type VerifiedName_VerifiedOne struct {
	VerifiedOne1         *uint64  `protobuf:"varint,1,opt,name=verifiedOne1" json:"verifiedOne1,omitempty"`
	VerifiedOne2         *string  `protobuf:"bytes,2,opt,name=verifiedOne2" json:"verifiedOne2,omitempty"`
	VerifiedOne4         *string  `protobuf:"bytes,4,opt,name=verifiedOne4" json:"verifiedOne4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifiedName_VerifiedOne) Reset()         { *m = VerifiedName_VerifiedOne{} }
func (m *VerifiedName_VerifiedOne) String() string { return proto.CompactTextString(m) }
func (*VerifiedName_VerifiedOne) ProtoMessage()    {}
func (*VerifiedName_VerifiedOne) Descriptor() ([]byte, []int) {
	return fileDescriptor_39cdc64788007a21, []int{0, 0}
}

func (m *VerifiedName_VerifiedOne) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifiedName_VerifiedOne.Unmarshal(m, b)
}
func (m *VerifiedName_VerifiedOne) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifiedName_VerifiedOne.Marshal(b, m, deterministic)
}
func (m *VerifiedName_VerifiedOne) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifiedName_VerifiedOne.Merge(m, src)
}
func (m *VerifiedName_VerifiedOne) XXX_Size() int {
	return xxx_messageInfo_VerifiedName_VerifiedOne.Size(m)
}
func (m *VerifiedName_VerifiedOne) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifiedName_VerifiedOne.DiscardUnknown(m)
}

var xxx_messageInfo_VerifiedName_VerifiedOne proto.InternalMessageInfo

func (m *VerifiedName_VerifiedOne) GetVerifiedOne1() uint64 {
	if m != nil && m.VerifiedOne1 != nil {
		return *m.VerifiedOne1
	}
	return 0
}

func (m *VerifiedName_VerifiedOne) GetVerifiedOne2() string {
	if m != nil && m.VerifiedOne2 != nil {
		return *m.VerifiedOne2
	}
	return ""
}

func (m *VerifiedName_VerifiedOne) GetVerifiedOne4() string {
	if m != nil && m.VerifiedOne4 != nil {
		return *m.VerifiedOne4
	}
	return ""
}

func init() {
	proto.RegisterType((*VerifiedName)(nil), "waproto.VerifiedName")
	proto.RegisterType((*VerifiedName_VerifiedOne)(nil), "waproto.VerifiedName.VerifiedOne")
}

func init() { proto.RegisterFile("verified.proto", fileDescriptor_39cdc64788007a21) }

var fileDescriptor_39cdc64788007a21 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4b, 0x2d, 0xca,
	0x4c, 0xcb, 0x4c, 0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4f, 0x04, 0x33,
	0x94, 0x3e, 0x30, 0x72, 0xf1, 0x84, 0x41, 0xe5, 0xfc, 0x12, 0x73, 0x53, 0x85, 0x9c, 0xb9, 0xb8,
	0x61, 0x6a, 0xfd, 0xf3, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x14, 0xf5, 0xa0, 0xea,
	0xf5, 0x90, 0xd5, 0xc2, 0x39, 0xfe, 0x79, 0xa9, 0x41, 0xc8, 0xba, 0x84, 0x14, 0x10, 0x86, 0x84,
	0xe4, 0x97, 0x4b, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x04, 0x21, 0x0b, 0x49, 0x55, 0x72, 0x71, 0x23,
	0xe9, 0x16, 0x52, 0xe2, 0xe2, 0x41, 0xd2, 0x6f, 0x08, 0xb6, 0x96, 0x25, 0x08, 0x45, 0x0c, 0x4d,
	0x8d, 0x11, 0xd8, 0x54, 0x4e, 0x14, 0x35, 0x46, 0x68, 0x6a, 0x4c, 0x24, 0x58, 0x30, 0xd4, 0x98,
	0x00, 0x02, 0x00, 0x00, 0xff, 0xff, 0x90, 0x26, 0x26, 0x31, 0x0c, 0x01, 0x00, 0x00,
}
