// Code generated by protoc-gen-go. DO NOT EDIT.
// source: whatsapp-noiseprotocol-handshake.proto

package whatsapp_noiseprotocol_handshake

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientPayload_ClientFeature int32

const (
	ClientPayload_NONE ClientPayload_ClientFeature = 0
)

var ClientPayload_ClientFeature_name = map[int32]string{
	0: "NONE",
}

var ClientPayload_ClientFeature_value = map[string]int32{
	"NONE": 0,
}

func (x ClientPayload_ClientFeature) Enum() *ClientPayload_ClientFeature {
	p := new(ClientPayload_ClientFeature)
	*p = x
	return p
}

func (x ClientPayload_ClientFeature) String() string {
	return proto.EnumName(ClientPayload_ClientFeature_name, int32(x))
}

func (x *ClientPayload_ClientFeature) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClientPayload_ClientFeature_value, data, "ClientPayload_ClientFeature")
	if err != nil {
		return err
	}
	*x = ClientPayload_ClientFeature(value)
	return nil
}

func (ClientPayload_ClientFeature) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{0, 0}
}

type ClientPayload_ConnectType int32

const (
	ClientPayload_UNKNOWN ClientPayload_ConnectType = 0
	ClientPayload_WIFI    ClientPayload_ConnectType = 1
	ClientPayload_EDGE    ClientPayload_ConnectType = 100
	ClientPayload_IDEN    ClientPayload_ConnectType = 101
	ClientPayload_UMTS    ClientPayload_ConnectType = 102
	ClientPayload_EVDO    ClientPayload_ConnectType = 103
	ClientPayload_GPRS    ClientPayload_ConnectType = 104
	ClientPayload_HSDPA   ClientPayload_ConnectType = 105
	ClientPayload_HSUPA   ClientPayload_ConnectType = 106
	ClientPayload_HSPA    ClientPayload_ConnectType = 107
	ClientPayload_CDMA    ClientPayload_ConnectType = 108
	ClientPayload_ONExRTT ClientPayload_ConnectType = 109
	ClientPayload_EHRPD   ClientPayload_ConnectType = 110
	ClientPayload_LTE     ClientPayload_ConnectType = 111
	ClientPayload_HSPAP   ClientPayload_ConnectType = 112
)

var ClientPayload_ConnectType_name = map[int32]string{
	0:   "UNKNOWN",
	1:   "WIFI",
	100: "EDGE",
	101: "IDEN",
	102: "UMTS",
	103: "EVDO",
	104: "GPRS",
	105: "HSDPA",
	106: "HSUPA",
	107: "HSPA",
	108: "CDMA",
	109: "ONExRTT",
	110: "EHRPD",
	111: "LTE",
	112: "HSPAP",
}

var ClientPayload_ConnectType_value = map[string]int32{
	"UNKNOWN": 0,
	"WIFI":    1,
	"EDGE":    100,
	"IDEN":    101,
	"UMTS":    102,
	"EVDO":    103,
	"GPRS":    104,
	"HSDPA":   105,
	"HSUPA":   106,
	"HSPA":    107,
	"CDMA":    108,
	"ONExRTT": 109,
	"EHRPD":   110,
	"LTE":     111,
	"HSPAP":   112,
}

func (x ClientPayload_ConnectType) Enum() *ClientPayload_ConnectType {
	p := new(ClientPayload_ConnectType)
	*p = x
	return p
}

func (x ClientPayload_ConnectType) String() string {
	return proto.EnumName(ClientPayload_ConnectType_name, int32(x))
}

func (x *ClientPayload_ConnectType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClientPayload_ConnectType_value, data, "ClientPayload_ConnectType")
	if err != nil {
		return err
	}
	*x = ClientPayload_ConnectType(value)
	return nil
}

func (ClientPayload_ConnectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{0, 1}
}

type ClientPayload_ConnectReason int32

const (
	ClientPayload_REASON_0 ClientPayload_ConnectReason = 0
	ClientPayload_REASON_1 ClientPayload_ConnectReason = 1
	ClientPayload_REASON_2 ClientPayload_ConnectReason = 2
	ClientPayload_REASON_3 ClientPayload_ConnectReason = 3
	ClientPayload_REASON_4 ClientPayload_ConnectReason = 4
	ClientPayload_REASON_5 ClientPayload_ConnectReason = 6
)

var ClientPayload_ConnectReason_name = map[int32]string{
	0: "REASON_0",
	1: "REASON_1",
	2: "REASON_2",
	3: "REASON_3",
	4: "REASON_4",
	6: "REASON_5",
}

var ClientPayload_ConnectReason_value = map[string]int32{
	"REASON_0": 0,
	"REASON_1": 1,
	"REASON_2": 2,
	"REASON_3": 3,
	"REASON_4": 4,
	"REASON_5": 6,
}

func (x ClientPayload_ConnectReason) Enum() *ClientPayload_ConnectReason {
	p := new(ClientPayload_ConnectReason)
	*p = x
	return p
}

func (x ClientPayload_ConnectReason) String() string {
	return proto.EnumName(ClientPayload_ConnectReason_name, int32(x))
}

func (x *ClientPayload_ConnectReason) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClientPayload_ConnectReason_value, data, "ClientPayload_ConnectReason")
	if err != nil {
		return err
	}
	*x = ClientPayload_ConnectReason(value)
	return nil
}

func (ClientPayload_ConnectReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{0, 2}
}

type ClientPayload_IosAppExtension int32

const (
	ClientPayload_EXT_0 ClientPayload_IosAppExtension = 0
	ClientPayload_EXT_1 ClientPayload_IosAppExtension = 1
	ClientPayload_EXT_2 ClientPayload_IosAppExtension = 2
)

var ClientPayload_IosAppExtension_name = map[int32]string{
	0: "EXT_0",
	1: "EXT_1",
	2: "EXT_2",
}

var ClientPayload_IosAppExtension_value = map[string]int32{
	"EXT_0": 0,
	"EXT_1": 1,
	"EXT_2": 2,
}

func (x ClientPayload_IosAppExtension) Enum() *ClientPayload_IosAppExtension {
	p := new(ClientPayload_IosAppExtension)
	*p = x
	return p
}

func (x ClientPayload_IosAppExtension) String() string {
	return proto.EnumName(ClientPayload_IosAppExtension_name, int32(x))
}

func (x *ClientPayload_IosAppExtension) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClientPayload_IosAppExtension_value, data, "ClientPayload_IosAppExtension")
	if err != nil {
		return err
	}
	*x = ClientPayload_IosAppExtension(value)
	return nil
}

func (ClientPayload_IosAppExtension) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{0, 3}
}

type ClientPayload_DnsSource_DnsMethod int32

const (
	ClientPayload_DnsSource_METHOD_0 ClientPayload_DnsSource_DnsMethod = 0
	ClientPayload_DnsSource_METHOD_1 ClientPayload_DnsSource_DnsMethod = 1
	ClientPayload_DnsSource_METHOD_2 ClientPayload_DnsSource_DnsMethod = 2
	ClientPayload_DnsSource_METHOD_3 ClientPayload_DnsSource_DnsMethod = 3
)

var ClientPayload_DnsSource_DnsMethod_name = map[int32]string{
	0: "METHOD_0",
	1: "METHOD_1",
	2: "METHOD_2",
	3: "METHOD_3",
}

var ClientPayload_DnsSource_DnsMethod_value = map[string]int32{
	"METHOD_0": 0,
	"METHOD_1": 1,
	"METHOD_2": 2,
	"METHOD_3": 3,
}

func (x ClientPayload_DnsSource_DnsMethod) Enum() *ClientPayload_DnsSource_DnsMethod {
	p := new(ClientPayload_DnsSource_DnsMethod)
	*p = x
	return p
}

func (x ClientPayload_DnsSource_DnsMethod) String() string {
	return proto.EnumName(ClientPayload_DnsSource_DnsMethod_name, int32(x))
}

func (x *ClientPayload_DnsSource_DnsMethod) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClientPayload_DnsSource_DnsMethod_value, data, "ClientPayload_DnsSource_DnsMethod")
	if err != nil {
		return err
	}
	*x = ClientPayload_DnsSource_DnsMethod(value)
	return nil
}

func (ClientPayload_DnsSource_DnsMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{0, 0, 0}
}

type ClientPayload_UserAgent_Platform int32

const (
	ClientPayload_UserAgent_ANDROID       ClientPayload_UserAgent_Platform = 0
	ClientPayload_UserAgent_IOS           ClientPayload_UserAgent_Platform = 1
	ClientPayload_UserAgent_WINDOWS_PHONE ClientPayload_UserAgent_Platform = 2
	ClientPayload_UserAgent_BLACKBERRY    ClientPayload_UserAgent_Platform = 3
	ClientPayload_UserAgent_BLACKBERRYX   ClientPayload_UserAgent_Platform = 4
	ClientPayload_UserAgent_S40           ClientPayload_UserAgent_Platform = 5
	ClientPayload_UserAgent_S60           ClientPayload_UserAgent_Platform = 6
	ClientPayload_UserAgent_PYTHON_CLIENT ClientPayload_UserAgent_Platform = 7
	ClientPayload_UserAgent_TIZEN         ClientPayload_UserAgent_Platform = 8
	ClientPayload_UserAgent_ENTERPRISE    ClientPayload_UserAgent_Platform = 9
	ClientPayload_UserAgent_PLATFORM_10   ClientPayload_UserAgent_Platform = 10
	ClientPayload_UserAgent_PLATFORM_11   ClientPayload_UserAgent_Platform = 11
)

var ClientPayload_UserAgent_Platform_name = map[int32]string{
	0:  "ANDROID",
	1:  "IOS",
	2:  "WINDOWS_PHONE",
	3:  "BLACKBERRY",
	4:  "BLACKBERRYX",
	5:  "S40",
	6:  "S60",
	7:  "PYTHON_CLIENT",
	8:  "TIZEN",
	9:  "ENTERPRISE",
	10: "PLATFORM_10",
	11: "PLATFORM_11",
}

var ClientPayload_UserAgent_Platform_value = map[string]int32{
	"ANDROID":       0,
	"IOS":           1,
	"WINDOWS_PHONE": 2,
	"BLACKBERRY":    3,
	"BLACKBERRYX":   4,
	"S40":           5,
	"S60":           6,
	"PYTHON_CLIENT": 7,
	"TIZEN":         8,
	"ENTERPRISE":    9,
	"PLATFORM_10":   10,
	"PLATFORM_11":   11,
}

func (x ClientPayload_UserAgent_Platform) Enum() *ClientPayload_UserAgent_Platform {
	p := new(ClientPayload_UserAgent_Platform)
	*p = x
	return p
}

func (x ClientPayload_UserAgent_Platform) String() string {
	return proto.EnumName(ClientPayload_UserAgent_Platform_name, int32(x))
}

func (x *ClientPayload_UserAgent_Platform) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClientPayload_UserAgent_Platform_value, data, "ClientPayload_UserAgent_Platform")
	if err != nil {
		return err
	}
	*x = ClientPayload_UserAgent_Platform(value)
	return nil
}

func (ClientPayload_UserAgent_Platform) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{0, 1, 0}
}

type ClientPayload_UserAgent_ReleaseChannel int32

const (
	ClientPayload_UserAgent_RELEASE ClientPayload_UserAgent_ReleaseChannel = 0
	ClientPayload_UserAgent_BETA    ClientPayload_UserAgent_ReleaseChannel = 1
	ClientPayload_UserAgent_ALPHA   ClientPayload_UserAgent_ReleaseChannel = 2
	ClientPayload_UserAgent_DEBUG   ClientPayload_UserAgent_ReleaseChannel = 3
)

var ClientPayload_UserAgent_ReleaseChannel_name = map[int32]string{
	0: "RELEASE",
	1: "BETA",
	2: "ALPHA",
	3: "DEBUG",
}

var ClientPayload_UserAgent_ReleaseChannel_value = map[string]int32{
	"RELEASE": 0,
	"BETA":    1,
	"ALPHA":   2,
	"DEBUG":   3,
}

func (x ClientPayload_UserAgent_ReleaseChannel) Enum() *ClientPayload_UserAgent_ReleaseChannel {
	p := new(ClientPayload_UserAgent_ReleaseChannel)
	*p = x
	return p
}

func (x ClientPayload_UserAgent_ReleaseChannel) String() string {
	return proto.EnumName(ClientPayload_UserAgent_ReleaseChannel_name, int32(x))
}

func (x *ClientPayload_UserAgent_ReleaseChannel) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClientPayload_UserAgent_ReleaseChannel_value, data, "ClientPayload_UserAgent_ReleaseChannel")
	if err != nil {
		return err
	}
	*x = ClientPayload_UserAgent_ReleaseChannel(value)
	return nil
}

func (ClientPayload_UserAgent_ReleaseChannel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{0, 1, 1}
}

type ClientPayload struct {
	Username            *uint64                        `protobuf:"varint,1,opt,name=username" json:"username,omitempty"`
	Passive             *bool                          `protobuf:"varint,3,opt,name=passive" json:"passive,omitempty"`
	ClientFeatures      []ClientPayload_ClientFeature  `protobuf:"varint,4,rep,name=client_features,json=clientFeatures,enum=ClientPayload_ClientFeature" json:"client_features,omitempty"`
	UserAgent           *ClientPayload_UserAgent       `protobuf:"bytes,5,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	WebInfo             *ClientPayload_WebInfo         `protobuf:"bytes,6,opt,name=web_info,json=webInfo" json:"web_info,omitempty"`
	PushName            *string                        `protobuf:"bytes,7,opt,name=push_name,json=pushName" json:"push_name,omitempty"`
	SessionId           *int32                         `protobuf:"fixed32,9,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	ShortConnect        *bool                          `protobuf:"varint,10,opt,name=short_connect,json=shortConnect" json:"short_connect,omitempty"`
	ConnectType         *ClientPayload_ConnectType     `protobuf:"varint,12,opt,name=connect_type,json=connectType,enum=ClientPayload_ConnectType" json:"connect_type,omitempty"`
	ConnectReason       *ClientPayload_ConnectReason   `protobuf:"varint,13,opt,name=connect_reason,json=connectReason,enum=ClientPayload_ConnectReason" json:"connect_reason,omitempty"`
	Shards              []int32                        `protobuf:"fixed32,14,rep,name=shards" json:"shards,omitempty"`
	DnsSource           *ClientPayload_DnsSource       `protobuf:"bytes,15,opt,name=dns_source,json=dnsSource" json:"dns_source,omitempty"`
	ConnectAttemptCount *int32                         `protobuf:"fixed32,16,opt,name=connect_attempt_count,json=connectAttemptCount" json:"connect_attempt_count,omitempty"`
	Oc                  *bool                          `protobuf:"varint,23,opt,name=oc" json:"oc,omitempty"`
	Lc                  *uint32                        `protobuf:"varint,24,opt,name=lc" json:"lc,omitempty"`
	IosAppExtension     *ClientPayload_IosAppExtension `protobuf:"varint,30,opt,name=ios_app_extension,json=iosAppExtension,enum=ClientPayload_IosAppExtension" json:"ios_app_extension,omitempty"`
	FbAppId             *uint64                        `protobuf:"varint,31,opt,name=fb_app_id,json=fbAppId" json:"fb_app_id,omitempty"`
	// 128-bit UUID https://www.internalfb.com/intern/wiki/How-do-we-uniquely-identify-devices/device-id/
	FbDeviceId           []byte   `protobuf:"bytes,32,opt,name=fb_device_id,json=fbDeviceId" json:"fb_device_id,omitempty"`
	Ok_36                *uint32  `protobuf:"varint,36,opt,name=ok_36,json=ok36" json:"ok_36,omitempty"`
	Ok_37                *uint32  `protobuf:"varint,37,opt,name=ok_37,json=ok37" json:"ok_37,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientPayload) Reset()         { *m = ClientPayload{} }
func (m *ClientPayload) String() string { return proto.CompactTextString(m) }
func (*ClientPayload) ProtoMessage()    {}
func (*ClientPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{0}
}

func (m *ClientPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientPayload.Unmarshal(m, b)
}
func (m *ClientPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientPayload.Marshal(b, m, deterministic)
}
func (m *ClientPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPayload.Merge(m, src)
}
func (m *ClientPayload) XXX_Size() int {
	return xxx_messageInfo_ClientPayload.Size(m)
}
func (m *ClientPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPayload proto.InternalMessageInfo

func (m *ClientPayload) GetUsername() uint64 {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return 0
}

func (m *ClientPayload) GetPassive() bool {
	if m != nil && m.Passive != nil {
		return *m.Passive
	}
	return false
}

func (m *ClientPayload) GetClientFeatures() []ClientPayload_ClientFeature {
	if m != nil {
		return m.ClientFeatures
	}
	return nil
}

func (m *ClientPayload) GetUserAgent() *ClientPayload_UserAgent {
	if m != nil {
		return m.UserAgent
	}
	return nil
}

func (m *ClientPayload) GetWebInfo() *ClientPayload_WebInfo {
	if m != nil {
		return m.WebInfo
	}
	return nil
}

func (m *ClientPayload) GetPushName() string {
	if m != nil && m.PushName != nil {
		return *m.PushName
	}
	return ""
}

func (m *ClientPayload) GetSessionId() int32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *ClientPayload) GetShortConnect() bool {
	if m != nil && m.ShortConnect != nil {
		return *m.ShortConnect
	}
	return false
}

func (m *ClientPayload) GetConnectType() ClientPayload_ConnectType {
	if m != nil && m.ConnectType != nil {
		return *m.ConnectType
	}
	return ClientPayload_UNKNOWN
}

func (m *ClientPayload) GetConnectReason() ClientPayload_ConnectReason {
	if m != nil && m.ConnectReason != nil {
		return *m.ConnectReason
	}
	return ClientPayload_REASON_0
}

func (m *ClientPayload) GetShards() []int32 {
	if m != nil {
		return m.Shards
	}
	return nil
}

func (m *ClientPayload) GetDnsSource() *ClientPayload_DnsSource {
	if m != nil {
		return m.DnsSource
	}
	return nil
}

func (m *ClientPayload) GetConnectAttemptCount() int32 {
	if m != nil && m.ConnectAttemptCount != nil {
		return *m.ConnectAttemptCount
	}
	return 0
}

func (m *ClientPayload) GetOc() bool {
	if m != nil && m.Oc != nil {
		return *m.Oc
	}
	return false
}

func (m *ClientPayload) GetLc() uint32 {
	if m != nil && m.Lc != nil {
		return *m.Lc
	}
	return 0
}

func (m *ClientPayload) GetIosAppExtension() ClientPayload_IosAppExtension {
	if m != nil && m.IosAppExtension != nil {
		return *m.IosAppExtension
	}
	return ClientPayload_EXT_0
}

func (m *ClientPayload) GetFbAppId() uint64 {
	if m != nil && m.FbAppId != nil {
		return *m.FbAppId
	}
	return 0
}

func (m *ClientPayload) GetFbDeviceId() []byte {
	if m != nil {
		return m.FbDeviceId
	}
	return nil
}

func (m *ClientPayload) GetOk_36() uint32 {
	if m != nil && m.Ok_36 != nil {
		return *m.Ok_36
	}
	return 0
}

func (m *ClientPayload) GetOk_37() uint32 {
	if m != nil && m.Ok_37 != nil {
		return *m.Ok_37
	}
	return 0
}

type ClientPayload_DnsSource struct {
	DnsMethod            *ClientPayload_DnsSource_DnsMethod `protobuf:"varint,15,opt,name=dnsMethod,enum=ClientPayload_DnsSource_DnsMethod" json:"dnsMethod,omitempty"`
	AppCached            *bool                              `protobuf:"varint,16,opt,name=appCached" json:"appCached,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ClientPayload_DnsSource) Reset()         { *m = ClientPayload_DnsSource{} }
func (m *ClientPayload_DnsSource) String() string { return proto.CompactTextString(m) }
func (*ClientPayload_DnsSource) ProtoMessage()    {}
func (*ClientPayload_DnsSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{0, 0}
}

func (m *ClientPayload_DnsSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientPayload_DnsSource.Unmarshal(m, b)
}
func (m *ClientPayload_DnsSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientPayload_DnsSource.Marshal(b, m, deterministic)
}
func (m *ClientPayload_DnsSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPayload_DnsSource.Merge(m, src)
}
func (m *ClientPayload_DnsSource) XXX_Size() int {
	return xxx_messageInfo_ClientPayload_DnsSource.Size(m)
}
func (m *ClientPayload_DnsSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPayload_DnsSource.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPayload_DnsSource proto.InternalMessageInfo

func (m *ClientPayload_DnsSource) GetDnsMethod() ClientPayload_DnsSource_DnsMethod {
	if m != nil && m.DnsMethod != nil {
		return *m.DnsMethod
	}
	return ClientPayload_DnsSource_METHOD_0
}

func (m *ClientPayload_DnsSource) GetAppCached() bool {
	if m != nil && m.AppCached != nil {
		return *m.AppCached
	}
	return false
}

type ClientPayload_UserAgent struct {
	Platform                       *ClientPayload_UserAgent_Platform       `protobuf:"varint,1,opt,name=platform,enum=ClientPayload_UserAgent_Platform" json:"platform,omitempty"`
	AppVersion                     *ClientPayload_UserAgent_AppVersion     `protobuf:"bytes,2,opt,name=app_version,json=appVersion" json:"app_version,omitempty"`
	Mcc                            *string                                 `protobuf:"bytes,3,opt,name=mcc" json:"mcc,omitempty"`
	Mnc                            *string                                 `protobuf:"bytes,4,opt,name=mnc" json:"mnc,omitempty"`
	OsVersion                      *string                                 `protobuf:"bytes,5,opt,name=os_version,json=osVersion" json:"os_version,omitempty"`
	Manufacturer                   *string                                 `protobuf:"bytes,6,opt,name=manufacturer" json:"manufacturer,omitempty"`
	Device                         *string                                 `protobuf:"bytes,7,opt,name=device" json:"device,omitempty"`
	OsBuildNumber                  *string                                 `protobuf:"bytes,8,opt,name=os_build_number,json=osBuildNumber" json:"os_build_number,omitempty"`
	PhoneId                        *string                                 `protobuf:"bytes,9,opt,name=phone_id,json=phoneId" json:"phone_id,omitempty"`
	ReleaseChannel                 *ClientPayload_UserAgent_ReleaseChannel `protobuf:"varint,10,opt,name=release_channel,json=releaseChannel,enum=ClientPayload_UserAgent_ReleaseChannel" json:"release_channel,omitempty"`
	LocaleLanguageIso_639_1        *string                                 `protobuf:"bytes,11,opt,name=locale_language_iso_639_1,json=localeLanguageIso6391" json:"locale_language_iso_639_1,omitempty"`
	LocaleCountryIso_3166_1Alpha_2 *string                                 `protobuf:"bytes,12,opt,name=locale_country_iso_3166_1_alpha_2,json=localeCountryIso31661Alpha2" json:"locale_country_iso_3166_1_alpha_2,omitempty"`
	XXX_NoUnkeyedLiteral           struct{}                                `json:"-"`
	XXX_unrecognized               []byte                                  `json:"-"`
	XXX_sizecache                  int32                                   `json:"-"`
}

func (m *ClientPayload_UserAgent) Reset()         { *m = ClientPayload_UserAgent{} }
func (m *ClientPayload_UserAgent) String() string { return proto.CompactTextString(m) }
func (*ClientPayload_UserAgent) ProtoMessage()    {}
func (*ClientPayload_UserAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{0, 1}
}

func (m *ClientPayload_UserAgent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientPayload_UserAgent.Unmarshal(m, b)
}
func (m *ClientPayload_UserAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientPayload_UserAgent.Marshal(b, m, deterministic)
}
func (m *ClientPayload_UserAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPayload_UserAgent.Merge(m, src)
}
func (m *ClientPayload_UserAgent) XXX_Size() int {
	return xxx_messageInfo_ClientPayload_UserAgent.Size(m)
}
func (m *ClientPayload_UserAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPayload_UserAgent.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPayload_UserAgent proto.InternalMessageInfo

func (m *ClientPayload_UserAgent) GetPlatform() ClientPayload_UserAgent_Platform {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return ClientPayload_UserAgent_ANDROID
}

func (m *ClientPayload_UserAgent) GetAppVersion() *ClientPayload_UserAgent_AppVersion {
	if m != nil {
		return m.AppVersion
	}
	return nil
}

func (m *ClientPayload_UserAgent) GetMcc() string {
	if m != nil && m.Mcc != nil {
		return *m.Mcc
	}
	return ""
}

func (m *ClientPayload_UserAgent) GetMnc() string {
	if m != nil && m.Mnc != nil {
		return *m.Mnc
	}
	return ""
}

func (m *ClientPayload_UserAgent) GetOsVersion() string {
	if m != nil && m.OsVersion != nil {
		return *m.OsVersion
	}
	return ""
}

func (m *ClientPayload_UserAgent) GetManufacturer() string {
	if m != nil && m.Manufacturer != nil {
		return *m.Manufacturer
	}
	return ""
}

func (m *ClientPayload_UserAgent) GetDevice() string {
	if m != nil && m.Device != nil {
		return *m.Device
	}
	return ""
}

func (m *ClientPayload_UserAgent) GetOsBuildNumber() string {
	if m != nil && m.OsBuildNumber != nil {
		return *m.OsBuildNumber
	}
	return ""
}

func (m *ClientPayload_UserAgent) GetPhoneId() string {
	if m != nil && m.PhoneId != nil {
		return *m.PhoneId
	}
	return ""
}

func (m *ClientPayload_UserAgent) GetReleaseChannel() ClientPayload_UserAgent_ReleaseChannel {
	if m != nil && m.ReleaseChannel != nil {
		return *m.ReleaseChannel
	}
	return ClientPayload_UserAgent_RELEASE
}

func (m *ClientPayload_UserAgent) GetLocaleLanguageIso_639_1() string {
	if m != nil && m.LocaleLanguageIso_639_1 != nil {
		return *m.LocaleLanguageIso_639_1
	}
	return ""
}

func (m *ClientPayload_UserAgent) GetLocaleCountryIso_3166_1Alpha_2() string {
	if m != nil && m.LocaleCountryIso_3166_1Alpha_2 != nil {
		return *m.LocaleCountryIso_3166_1Alpha_2
	}
	return ""
}

type ClientPayload_UserAgent_AppVersion struct {
	Primary              *uint32  `protobuf:"varint,1,opt,name=primary" json:"primary,omitempty"`
	Secondary            *uint32  `protobuf:"varint,2,opt,name=secondary" json:"secondary,omitempty"`
	Tertiary             *uint32  `protobuf:"varint,3,opt,name=tertiary" json:"tertiary,omitempty"`
	Quaternary           *uint32  `protobuf:"varint,4,opt,name=quaternary" json:"quaternary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientPayload_UserAgent_AppVersion) Reset()         { *m = ClientPayload_UserAgent_AppVersion{} }
func (m *ClientPayload_UserAgent_AppVersion) String() string { return proto.CompactTextString(m) }
func (*ClientPayload_UserAgent_AppVersion) ProtoMessage()    {}
func (*ClientPayload_UserAgent_AppVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{0, 1, 0}
}

func (m *ClientPayload_UserAgent_AppVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientPayload_UserAgent_AppVersion.Unmarshal(m, b)
}
func (m *ClientPayload_UserAgent_AppVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientPayload_UserAgent_AppVersion.Marshal(b, m, deterministic)
}
func (m *ClientPayload_UserAgent_AppVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPayload_UserAgent_AppVersion.Merge(m, src)
}
func (m *ClientPayload_UserAgent_AppVersion) XXX_Size() int {
	return xxx_messageInfo_ClientPayload_UserAgent_AppVersion.Size(m)
}
func (m *ClientPayload_UserAgent_AppVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPayload_UserAgent_AppVersion.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPayload_UserAgent_AppVersion proto.InternalMessageInfo

func (m *ClientPayload_UserAgent_AppVersion) GetPrimary() uint32 {
	if m != nil && m.Primary != nil {
		return *m.Primary
	}
	return 0
}

func (m *ClientPayload_UserAgent_AppVersion) GetSecondary() uint32 {
	if m != nil && m.Secondary != nil {
		return *m.Secondary
	}
	return 0
}

func (m *ClientPayload_UserAgent_AppVersion) GetTertiary() uint32 {
	if m != nil && m.Tertiary != nil {
		return *m.Tertiary
	}
	return 0
}

func (m *ClientPayload_UserAgent_AppVersion) GetQuaternary() uint32 {
	if m != nil && m.Quaternary != nil {
		return *m.Quaternary
	}
	return 0
}

type ClientPayload_WebInfo struct {
	RefToken             *string                            `protobuf:"bytes,1,opt,name=ref_token,json=refToken" json:"ref_token,omitempty"`
	Version              *string                            `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	WebdPayload          *ClientPayload_WebInfo_WebdPayload `protobuf:"bytes,3,opt,name=webd_payload,json=webdPayload" json:"webd_payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ClientPayload_WebInfo) Reset()         { *m = ClientPayload_WebInfo{} }
func (m *ClientPayload_WebInfo) String() string { return proto.CompactTextString(m) }
func (*ClientPayload_WebInfo) ProtoMessage()    {}
func (*ClientPayload_WebInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{0, 2}
}

func (m *ClientPayload_WebInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientPayload_WebInfo.Unmarshal(m, b)
}
func (m *ClientPayload_WebInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientPayload_WebInfo.Marshal(b, m, deterministic)
}
func (m *ClientPayload_WebInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPayload_WebInfo.Merge(m, src)
}
func (m *ClientPayload_WebInfo) XXX_Size() int {
	return xxx_messageInfo_ClientPayload_WebInfo.Size(m)
}
func (m *ClientPayload_WebInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPayload_WebInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPayload_WebInfo proto.InternalMessageInfo

func (m *ClientPayload_WebInfo) GetRefToken() string {
	if m != nil && m.RefToken != nil {
		return *m.RefToken
	}
	return ""
}

func (m *ClientPayload_WebInfo) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *ClientPayload_WebInfo) GetWebdPayload() *ClientPayload_WebInfo_WebdPayload {
	if m != nil {
		return m.WebdPayload
	}
	return nil
}

type ClientPayload_WebInfo_WebdPayload struct {
	UsesParticipantInKey     *bool    `protobuf:"varint,1,opt,name=uses_participant_in_key,json=usesParticipantInKey" json:"uses_participant_in_key,omitempty"`
	SupportsStarredMessages  *bool    `protobuf:"varint,2,opt,name=supports_starred_messages,json=supportsStarredMessages" json:"supports_starred_messages,omitempty"`
	SupportsDocumentMessages *bool    `protobuf:"varint,3,opt,name=supports_document_messages,json=supportsDocumentMessages" json:"supports_document_messages,omitempty"`
	SupportsUrlMessages      *bool    `protobuf:"varint,4,opt,name=supports_url_messages,json=supportsUrlMessages" json:"supports_url_messages,omitempty"`
	SupportsMediaRetry       *bool    `protobuf:"varint,5,opt,name=supports_media_retry,json=supportsMediaRetry" json:"supports_media_retry,omitempty"`
	SupportsE2EImage         *bool    `protobuf:"varint,6,opt,name=supports_e2e_image,json=supportsE2eImage" json:"supports_e2e_image,omitempty"`
	SupportsE2EVideo         *bool    `protobuf:"varint,7,opt,name=supports_e2e_video,json=supportsE2eVideo" json:"supports_e2e_video,omitempty"`
	SupportsE2EAudio         *bool    `protobuf:"varint,8,opt,name=supports_e2e_audio,json=supportsE2eAudio" json:"supports_e2e_audio,omitempty"`
	SupportsE2EDocument      *bool    `protobuf:"varint,9,opt,name=supports_e2e_document,json=supportsE2eDocument" json:"supports_e2e_document,omitempty"`
	DocumentTypes            *string  `protobuf:"bytes,10,opt,name=document_types,json=documentTypes" json:"document_types,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *ClientPayload_WebInfo_WebdPayload) Reset()         { *m = ClientPayload_WebInfo_WebdPayload{} }
func (m *ClientPayload_WebInfo_WebdPayload) String() string { return proto.CompactTextString(m) }
func (*ClientPayload_WebInfo_WebdPayload) ProtoMessage()    {}
func (*ClientPayload_WebInfo_WebdPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{0, 2, 0}
}

func (m *ClientPayload_WebInfo_WebdPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientPayload_WebInfo_WebdPayload.Unmarshal(m, b)
}
func (m *ClientPayload_WebInfo_WebdPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientPayload_WebInfo_WebdPayload.Marshal(b, m, deterministic)
}
func (m *ClientPayload_WebInfo_WebdPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientPayload_WebInfo_WebdPayload.Merge(m, src)
}
func (m *ClientPayload_WebInfo_WebdPayload) XXX_Size() int {
	return xxx_messageInfo_ClientPayload_WebInfo_WebdPayload.Size(m)
}
func (m *ClientPayload_WebInfo_WebdPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientPayload_WebInfo_WebdPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ClientPayload_WebInfo_WebdPayload proto.InternalMessageInfo

func (m *ClientPayload_WebInfo_WebdPayload) GetUsesParticipantInKey() bool {
	if m != nil && m.UsesParticipantInKey != nil {
		return *m.UsesParticipantInKey
	}
	return false
}

func (m *ClientPayload_WebInfo_WebdPayload) GetSupportsStarredMessages() bool {
	if m != nil && m.SupportsStarredMessages != nil {
		return *m.SupportsStarredMessages
	}
	return false
}

func (m *ClientPayload_WebInfo_WebdPayload) GetSupportsDocumentMessages() bool {
	if m != nil && m.SupportsDocumentMessages != nil {
		return *m.SupportsDocumentMessages
	}
	return false
}

func (m *ClientPayload_WebInfo_WebdPayload) GetSupportsUrlMessages() bool {
	if m != nil && m.SupportsUrlMessages != nil {
		return *m.SupportsUrlMessages
	}
	return false
}

func (m *ClientPayload_WebInfo_WebdPayload) GetSupportsMediaRetry() bool {
	if m != nil && m.SupportsMediaRetry != nil {
		return *m.SupportsMediaRetry
	}
	return false
}

func (m *ClientPayload_WebInfo_WebdPayload) GetSupportsE2EImage() bool {
	if m != nil && m.SupportsE2EImage != nil {
		return *m.SupportsE2EImage
	}
	return false
}

func (m *ClientPayload_WebInfo_WebdPayload) GetSupportsE2EVideo() bool {
	if m != nil && m.SupportsE2EVideo != nil {
		return *m.SupportsE2EVideo
	}
	return false
}

func (m *ClientPayload_WebInfo_WebdPayload) GetSupportsE2EAudio() bool {
	if m != nil && m.SupportsE2EAudio != nil {
		return *m.SupportsE2EAudio
	}
	return false
}

func (m *ClientPayload_WebInfo_WebdPayload) GetSupportsE2EDocument() bool {
	if m != nil && m.SupportsE2EDocument != nil {
		return *m.SupportsE2EDocument
	}
	return false
}

func (m *ClientPayload_WebInfo_WebdPayload) GetDocumentTypes() string {
	if m != nil && m.DocumentTypes != nil {
		return *m.DocumentTypes
	}
	return ""
}

type HandshakeMessage struct {
	ClientHello          *HandshakeMessage_ClientHello  `protobuf:"bytes,2,opt,name=client_hello,json=clientHello" json:"client_hello,omitempty"`
	ServerHello          *HandshakeMessage_ServerHello  `protobuf:"bytes,3,opt,name=server_hello,json=serverHello" json:"server_hello,omitempty"`
	ClientFinish         *HandshakeMessage_ClientFinish `protobuf:"bytes,4,opt,name=client_finish,json=clientFinish" json:"client_finish,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *HandshakeMessage) Reset()         { *m = HandshakeMessage{} }
func (m *HandshakeMessage) String() string { return proto.CompactTextString(m) }
func (*HandshakeMessage) ProtoMessage()    {}
func (*HandshakeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{1}
}

func (m *HandshakeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeMessage.Unmarshal(m, b)
}
func (m *HandshakeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeMessage.Marshal(b, m, deterministic)
}
func (m *HandshakeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeMessage.Merge(m, src)
}
func (m *HandshakeMessage) XXX_Size() int {
	return xxx_messageInfo_HandshakeMessage.Size(m)
}
func (m *HandshakeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeMessage proto.InternalMessageInfo

func (m *HandshakeMessage) GetClientHello() *HandshakeMessage_ClientHello {
	if m != nil {
		return m.ClientHello
	}
	return nil
}

func (m *HandshakeMessage) GetServerHello() *HandshakeMessage_ServerHello {
	if m != nil {
		return m.ServerHello
	}
	return nil
}

func (m *HandshakeMessage) GetClientFinish() *HandshakeMessage_ClientFinish {
	if m != nil {
		return m.ClientFinish
	}
	return nil
}

type HandshakeMessage_ClientHello struct {
	Ephemeral            []byte   `protobuf:"bytes,1,opt,name=ephemeral" json:"ephemeral,omitempty"`
	Static               []byte   `protobuf:"bytes,2,opt,name=static" json:"static,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandshakeMessage_ClientHello) Reset()         { *m = HandshakeMessage_ClientHello{} }
func (m *HandshakeMessage_ClientHello) String() string { return proto.CompactTextString(m) }
func (*HandshakeMessage_ClientHello) ProtoMessage()    {}
func (*HandshakeMessage_ClientHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{1, 0}
}

func (m *HandshakeMessage_ClientHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeMessage_ClientHello.Unmarshal(m, b)
}
func (m *HandshakeMessage_ClientHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeMessage_ClientHello.Marshal(b, m, deterministic)
}
func (m *HandshakeMessage_ClientHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeMessage_ClientHello.Merge(m, src)
}
func (m *HandshakeMessage_ClientHello) XXX_Size() int {
	return xxx_messageInfo_HandshakeMessage_ClientHello.Size(m)
}
func (m *HandshakeMessage_ClientHello) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeMessage_ClientHello.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeMessage_ClientHello proto.InternalMessageInfo

func (m *HandshakeMessage_ClientHello) GetEphemeral() []byte {
	if m != nil {
		return m.Ephemeral
	}
	return nil
}

func (m *HandshakeMessage_ClientHello) GetStatic() []byte {
	if m != nil {
		return m.Static
	}
	return nil
}

func (m *HandshakeMessage_ClientHello) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type HandshakeMessage_ServerHello struct {
	Ephemeral            []byte   `protobuf:"bytes,1,opt,name=ephemeral" json:"ephemeral,omitempty"`
	Static               []byte   `protobuf:"bytes,2,opt,name=static" json:"static,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandshakeMessage_ServerHello) Reset()         { *m = HandshakeMessage_ServerHello{} }
func (m *HandshakeMessage_ServerHello) String() string { return proto.CompactTextString(m) }
func (*HandshakeMessage_ServerHello) ProtoMessage()    {}
func (*HandshakeMessage_ServerHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{1, 1}
}

func (m *HandshakeMessage_ServerHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeMessage_ServerHello.Unmarshal(m, b)
}
func (m *HandshakeMessage_ServerHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeMessage_ServerHello.Marshal(b, m, deterministic)
}
func (m *HandshakeMessage_ServerHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeMessage_ServerHello.Merge(m, src)
}
func (m *HandshakeMessage_ServerHello) XXX_Size() int {
	return xxx_messageInfo_HandshakeMessage_ServerHello.Size(m)
}
func (m *HandshakeMessage_ServerHello) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeMessage_ServerHello.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeMessage_ServerHello proto.InternalMessageInfo

func (m *HandshakeMessage_ServerHello) GetEphemeral() []byte {
	if m != nil {
		return m.Ephemeral
	}
	return nil
}

func (m *HandshakeMessage_ServerHello) GetStatic() []byte {
	if m != nil {
		return m.Static
	}
	return nil
}

func (m *HandshakeMessage_ServerHello) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type HandshakeMessage_ClientFinish struct {
	Static               []byte   `protobuf:"bytes,1,opt,name=static" json:"static,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandshakeMessage_ClientFinish) Reset()         { *m = HandshakeMessage_ClientFinish{} }
func (m *HandshakeMessage_ClientFinish) String() string { return proto.CompactTextString(m) }
func (*HandshakeMessage_ClientFinish) ProtoMessage()    {}
func (*HandshakeMessage_ClientFinish) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{1, 2}
}

func (m *HandshakeMessage_ClientFinish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeMessage_ClientFinish.Unmarshal(m, b)
}
func (m *HandshakeMessage_ClientFinish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeMessage_ClientFinish.Marshal(b, m, deterministic)
}
func (m *HandshakeMessage_ClientFinish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeMessage_ClientFinish.Merge(m, src)
}
func (m *HandshakeMessage_ClientFinish) XXX_Size() int {
	return xxx_messageInfo_HandshakeMessage_ClientFinish.Size(m)
}
func (m *HandshakeMessage_ClientFinish) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeMessage_ClientFinish.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeMessage_ClientFinish proto.InternalMessageInfo

func (m *HandshakeMessage_ClientFinish) GetStatic() []byte {
	if m != nil {
		return m.Static
	}
	return nil
}

func (m *HandshakeMessage_ClientFinish) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type NoiseCertificate struct {
	Details              []byte   `protobuf:"bytes,1,opt,name=details" json:"details,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoiseCertificate) Reset()         { *m = NoiseCertificate{} }
func (m *NoiseCertificate) String() string { return proto.CompactTextString(m) }
func (*NoiseCertificate) ProtoMessage()    {}
func (*NoiseCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{2}
}

func (m *NoiseCertificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoiseCertificate.Unmarshal(m, b)
}
func (m *NoiseCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoiseCertificate.Marshal(b, m, deterministic)
}
func (m *NoiseCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoiseCertificate.Merge(m, src)
}
func (m *NoiseCertificate) XXX_Size() int {
	return xxx_messageInfo_NoiseCertificate.Size(m)
}
func (m *NoiseCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_NoiseCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_NoiseCertificate proto.InternalMessageInfo

func (m *NoiseCertificate) GetDetails() []byte {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *NoiseCertificate) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type NoiseCertificate_Details struct {
	Serial               *uint32  `protobuf:"varint,1,opt,name=serial" json:"serial,omitempty"`
	Issuer               *string  `protobuf:"bytes,2,opt,name=issuer" json:"issuer,omitempty"`
	Expires              *uint64  `protobuf:"varint,3,opt,name=expires" json:"expires,omitempty"`
	Subject              *string  `protobuf:"bytes,4,opt,name=subject" json:"subject,omitempty"`
	Key                  []byte   `protobuf:"bytes,5,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoiseCertificate_Details) Reset()         { *m = NoiseCertificate_Details{} }
func (m *NoiseCertificate_Details) String() string { return proto.CompactTextString(m) }
func (*NoiseCertificate_Details) ProtoMessage()    {}
func (*NoiseCertificate_Details) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e42d3fdbf101ff, []int{2, 0}
}

func (m *NoiseCertificate_Details) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoiseCertificate_Details.Unmarshal(m, b)
}
func (m *NoiseCertificate_Details) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoiseCertificate_Details.Marshal(b, m, deterministic)
}
func (m *NoiseCertificate_Details) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoiseCertificate_Details.Merge(m, src)
}
func (m *NoiseCertificate_Details) XXX_Size() int {
	return xxx_messageInfo_NoiseCertificate_Details.Size(m)
}
func (m *NoiseCertificate_Details) XXX_DiscardUnknown() {
	xxx_messageInfo_NoiseCertificate_Details.DiscardUnknown(m)
}

var xxx_messageInfo_NoiseCertificate_Details proto.InternalMessageInfo

func (m *NoiseCertificate_Details) GetSerial() uint32 {
	if m != nil && m.Serial != nil {
		return *m.Serial
	}
	return 0
}

func (m *NoiseCertificate_Details) GetIssuer() string {
	if m != nil && m.Issuer != nil {
		return *m.Issuer
	}
	return ""
}

func (m *NoiseCertificate_Details) GetExpires() uint64 {
	if m != nil && m.Expires != nil {
		return *m.Expires
	}
	return 0
}

func (m *NoiseCertificate_Details) GetSubject() string {
	if m != nil && m.Subject != nil {
		return *m.Subject
	}
	return ""
}

func (m *NoiseCertificate_Details) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func init() {
	proto.RegisterEnum("ClientPayload_ClientFeature", ClientPayload_ClientFeature_name, ClientPayload_ClientFeature_value)
	proto.RegisterEnum("ClientPayload_ConnectType", ClientPayload_ConnectType_name, ClientPayload_ConnectType_value)
	proto.RegisterEnum("ClientPayload_ConnectReason", ClientPayload_ConnectReason_name, ClientPayload_ConnectReason_value)
	proto.RegisterEnum("ClientPayload_IosAppExtension", ClientPayload_IosAppExtension_name, ClientPayload_IosAppExtension_value)
	proto.RegisterEnum("ClientPayload_DnsSource_DnsMethod", ClientPayload_DnsSource_DnsMethod_name, ClientPayload_DnsSource_DnsMethod_value)
	proto.RegisterEnum("ClientPayload_UserAgent_Platform", ClientPayload_UserAgent_Platform_name, ClientPayload_UserAgent_Platform_value)
	proto.RegisterEnum("ClientPayload_UserAgent_ReleaseChannel", ClientPayload_UserAgent_ReleaseChannel_name, ClientPayload_UserAgent_ReleaseChannel_value)
	proto.RegisterType((*ClientPayload)(nil), "ClientPayload")
	proto.RegisterType((*ClientPayload_DnsSource)(nil), "ClientPayload.DnsSource")
	proto.RegisterType((*ClientPayload_UserAgent)(nil), "ClientPayload.UserAgent")
	proto.RegisterType((*ClientPayload_UserAgent_AppVersion)(nil), "ClientPayload.UserAgent.AppVersion")
	proto.RegisterType((*ClientPayload_WebInfo)(nil), "ClientPayload.WebInfo")
	proto.RegisterType((*ClientPayload_WebInfo_WebdPayload)(nil), "ClientPayload.WebInfo.WebdPayload")
	proto.RegisterType((*HandshakeMessage)(nil), "HandshakeMessage")
	proto.RegisterType((*HandshakeMessage_ClientHello)(nil), "HandshakeMessage.ClientHello")
	proto.RegisterType((*HandshakeMessage_ServerHello)(nil), "HandshakeMessage.ServerHello")
	proto.RegisterType((*HandshakeMessage_ClientFinish)(nil), "HandshakeMessage.ClientFinish")
	proto.RegisterType((*NoiseCertificate)(nil), "NoiseCertificate")
	proto.RegisterType((*NoiseCertificate_Details)(nil), "NoiseCertificate.Details")
}

func init() {
	proto.RegisterFile("whatsapp-noiseprotocol-handshake.proto", fileDescriptor_18e42d3fdbf101ff)
}

var fileDescriptor_18e42d3fdbf101ff = []byte{
	// 1786 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xcd, 0x72, 0xdb, 0xc8,
	0x11, 0x36, 0x48, 0xca, 0x24, 0x86, 0x3f, 0x9a, 0x1d, 0xaf, 0xd7, 0x30, 0xd7, 0xeb, 0x70, 0xb9,
	0xd9, 0x0d, 0x0f, 0x59, 0x97, 0x48, 0xed, 0xca, 0xd9, 0x54, 0x5c, 0x65, 0x88, 0x84, 0x4c, 0xc4,
	0x12, 0xc9, 0x1a, 0x52, 0xd6, 0x6e, 0xaa, 0x52, 0xa8, 0x21, 0x30, 0x14, 0xb1, 0x02, 0x31, 0x08,
	0x06, 0x90, 0xac, 0x53, 0x72, 0x4a, 0x55, 0xce, 0x79, 0x82, 0xdc, 0x73, 0xc8, 0x29, 0x2f, 0x91,
	0x47, 0xc8, 0xcb, 0xa4, 0x66, 0x30, 0xe0, 0x8f, 0x6c, 0xdd, 0x72, 0x62, 0x7f, 0xdd, 0x5f, 0xf7,
	0xcc, 0x34, 0xa6, 0x7b, 0x9a, 0xe0, 0x9b, 0x9b, 0x25, 0x49, 0x38, 0x89, 0xa2, 0x6f, 0x43, 0xe6,
	0x73, 0x1a, 0xc5, 0x2c, 0x61, 0x2e, 0x0b, 0xbe, 0x5d, 0x92, 0xd0, 0xe3, 0x4b, 0x72, 0x45, 0x5f,
	0x48, 0x55, 0xfb, 0xaf, 0x4f, 0x40, 0xbd, 0x1f, 0xf8, 0x34, 0x4c, 0x26, 0xe4, 0x36, 0x60, 0xc4,
	0x43, 0x4d, 0x50, 0x49, 0x39, 0x8d, 0x43, 0xb2, 0xa2, 0x86, 0xd6, 0xd2, 0x3a, 0x25, 0xbc, 0xc6,
	0xc8, 0x00, 0xe5, 0x88, 0x70, 0xee, 0x5f, 0x53, 0xa3, 0xd8, 0xd2, 0x3a, 0x15, 0x9c, 0x43, 0x64,
	0x81, 0x7d, 0x57, 0x86, 0x71, 0x16, 0x94, 0x24, 0x69, 0x4c, 0xb9, 0x51, 0x6a, 0x15, 0x3b, 0x8d,
	0xde, 0xb3, 0x17, 0x3b, 0xe1, 0x15, 0x3a, 0xc9, 0x48, 0xb8, 0xe1, 0x6e, 0x43, 0x8e, 0x5e, 0x02,
	0x20, 0x16, 0x73, 0xc8, 0x25, 0x0d, 0x13, 0x63, 0xaf, 0xa5, 0x75, 0xaa, 0x3d, 0xe3, 0x4e, 0x84,
	0x73, 0x4e, 0x63, 0x53, 0xd8, 0xb1, 0x9e, 0xe6, 0x22, 0xea, 0x82, 0xca, 0x0d, 0x9d, 0x3b, 0x7e,
	0xb8, 0x60, 0xc6, 0x43, 0xe9, 0xf6, 0xd9, 0x1d, 0xb7, 0x0b, 0x3a, 0xb7, 0xc3, 0x05, 0xc3, 0xe5,
	0x9b, 0x4c, 0x40, 0x9f, 0x03, 0x3d, 0x4a, 0xf9, 0xd2, 0x91, 0x27, 0x2d, 0xb7, 0xb4, 0x8e, 0x8e,
	0x2b, 0x42, 0x31, 0x12, 0x27, 0xfd, 0x02, 0x00, 0x4e, 0x39, 0xf7, 0x59, 0xe8, 0xf8, 0x9e, 0xa1,
	0xb7, 0xb4, 0xce, 0x3e, 0xd6, 0x95, 0xc6, 0xf6, 0xd0, 0x57, 0xa0, 0xce, 0x97, 0x2c, 0x4e, 0x1c,
	0x97, 0x85, 0x21, 0x75, 0x13, 0x03, 0xc8, 0x74, 0xd4, 0xa4, 0xb2, 0x9f, 0xe9, 0xd0, 0x2b, 0x50,
	0x53, 0x66, 0x27, 0xb9, 0x8d, 0xa8, 0x51, 0x6b, 0x69, 0x9d, 0x46, 0xaf, 0x79, 0x37, 0x21, 0x19,
	0x65, 0x76, 0x1b, 0x51, 0x5c, 0x75, 0x37, 0x00, 0xf5, 0x41, 0x23, 0x77, 0x8f, 0x29, 0xe1, 0x2c,
	0x34, 0xea, 0x32, 0xc0, 0xb3, 0x8f, 0x07, 0xc0, 0x92, 0x83, 0xeb, 0xee, 0x36, 0x44, 0x9f, 0x81,
	0x87, 0x7c, 0x49, 0x62, 0x8f, 0x1b, 0x8d, 0x56, 0xb1, 0xb3, 0x8f, 0x15, 0x12, 0x89, 0xf6, 0x42,
	0xee, 0x70, 0x96, 0xc6, 0x2e, 0x35, 0xf6, 0x3f, 0x9a, 0xe8, 0x41, 0xc8, 0xa7, 0xd2, 0x8e, 0x75,
	0x2f, 0x17, 0x51, 0x0f, 0x3c, 0xce, 0x77, 0x45, 0x92, 0x84, 0xae, 0x22, 0x91, 0x83, 0x34, 0x4c,
	0x0c, 0x28, 0x73, 0xf4, 0x48, 0x19, 0xcd, 0xcc, 0xd6, 0x17, 0x26, 0xd4, 0x00, 0x05, 0xe6, 0x1a,
	0x4f, 0x64, 0x8a, 0x0a, 0xcc, 0x15, 0x38, 0x70, 0x0d, 0xa3, 0xa5, 0x75, 0xea, 0xb8, 0x10, 0xb8,
	0xe8, 0xf7, 0xe0, 0x13, 0x9f, 0x71, 0x87, 0x44, 0x91, 0x43, 0xdf, 0x27, 0x34, 0x14, 0x49, 0x36,
	0x9e, 0xcb, 0xc3, 0x3e, 0xbf, 0xb3, 0x27, 0x9b, 0x71, 0x33, 0x8a, 0xac, 0x9c, 0x85, 0xf7, 0xfd,
	0x5d, 0x05, 0x6a, 0x02, 0x7d, 0x31, 0x97, 0xa1, 0x7c, 0xcf, 0xf8, 0x85, 0xbc, 0xbf, 0xe5, 0xc5,
	0xdc, 0x8c, 0x22, 0xdb, 0x43, 0x2d, 0x50, 0x5b, 0xcc, 0x1d, 0x8f, 0x5e, 0xfb, 0x2e, 0x15, 0xe6,
	0x56, 0x4b, 0xeb, 0xd4, 0x30, 0x58, 0xcc, 0x07, 0x52, 0x65, 0x7b, 0xe8, 0x11, 0xd8, 0x63, 0x57,
	0xce, 0xe1, 0x91, 0xf1, 0x4b, 0xb9, 0xb9, 0x12, 0xbb, 0x3a, 0x3c, 0xca, 0x95, 0x2f, 0x8d, 0xaf,
	0xd7, 0xca, 0x97, 0xcd, 0x7f, 0x69, 0x40, 0x5f, 0x27, 0x08, 0xbd, 0x06, 0x22, 0x45, 0x67, 0x34,
	0x59, 0x32, 0x4f, 0x66, 0xb3, 0xd1, 0x6b, 0xdf, 0x97, 0x4d, 0x21, 0x65, 0x4c, 0xbc, 0x71, 0x42,
	0xcf, 0x80, 0x4e, 0xa2, 0xa8, 0x4f, 0xdc, 0x25, 0xf5, 0x64, 0x2e, 0x2b, 0x78, 0xa3, 0x68, 0xf7,
	0xe5, 0x62, 0x8a, 0x5a, 0x03, 0x95, 0x33, 0x6b, 0x36, 0x1c, 0x0f, 0x9c, 0x03, 0xf8, 0x60, 0x0b,
	0x75, 0xa1, 0xb6, 0x85, 0x7a, 0xb0, 0xb0, 0x85, 0x0e, 0x61, 0xb1, 0xf9, 0x8f, 0x32, 0xd0, 0xd7,
	0xc5, 0x83, 0x5e, 0x81, 0x4a, 0x14, 0x90, 0x64, 0xc1, 0xe2, 0x95, 0xac, 0xf3, 0x46, 0xef, 0xcb,
	0xfb, 0x0a, 0xed, 0xc5, 0x44, 0x11, 0xf1, 0xda, 0x05, 0x0d, 0x40, 0x55, 0x24, 0xf9, 0x9a, 0xc6,
	0xf2, 0x6b, 0x15, 0xe4, 0x0d, 0xfa, 0xea, 0xde, 0x08, 0x66, 0x14, 0xbd, 0xcb, 0xa8, 0x18, 0x90,
	0xb5, 0x8c, 0x20, 0x28, 0xae, 0x5c, 0x57, 0x36, 0x13, 0x1d, 0x0b, 0x51, 0x6a, 0x42, 0xd7, 0x28,
	0x29, 0x4d, 0xe8, 0x8a, 0x52, 0x64, 0x7c, 0xbd, 0xd0, 0x9e, 0x34, 0xe8, 0x8c, 0xe7, 0x21, 0xda,
	0xa0, 0xb6, 0x22, 0x61, 0xba, 0x20, 0xae, 0x68, 0x21, 0xb1, 0xac, 0x7e, 0x1d, 0xef, 0xe8, 0x44,
	0x15, 0x64, 0x5f, 0x5d, 0xd5, 0xb9, 0x42, 0xe8, 0x1b, 0xb0, 0xcf, 0xb8, 0x33, 0x4f, 0xfd, 0xc0,
	0x73, 0xc2, 0x74, 0x35, 0xa7, 0xb1, 0x51, 0x91, 0x84, 0x3a, 0xe3, 0xc7, 0x42, 0x3b, 0x92, 0x4a,
	0xf4, 0x14, 0x54, 0xa2, 0x25, 0x0b, 0x69, 0xde, 0x0b, 0x74, 0x5c, 0x96, 0xd8, 0xf6, 0xd0, 0x04,
	0xec, 0xc7, 0x34, 0xa0, 0x84, 0x53, 0xc7, 0x5d, 0x92, 0x30, 0xa4, 0x81, 0xec, 0x05, 0x8d, 0xde,
	0xaf, 0xee, 0xcd, 0x05, 0xce, 0xf8, 0xfd, 0x8c, 0x8e, 0x1b, 0xf1, 0x0e, 0x46, 0xbf, 0x01, 0x4f,
	0x03, 0xe6, 0x92, 0x80, 0x3a, 0x01, 0x09, 0x2f, 0x53, 0x72, 0x49, 0x1d, 0x9f, 0x33, 0xe7, 0xe8,
	0xf0, 0x07, 0xa7, 0x6b, 0x54, 0xe5, 0xea, 0x8f, 0x33, 0xc2, 0xa9, 0xb2, 0xdb, 0x9c, 0x1d, 0x1d,
	0xfe, 0xd0, 0x45, 0x27, 0xe0, 0x4b, 0xe5, 0x29, 0x4b, 0x32, 0xbe, 0x95, 0x8e, 0x87, 0xdd, 0xa3,
	0x23, 0xa7, 0xeb, 0x90, 0x20, 0x5a, 0x12, 0xa7, 0x27, 0xbb, 0x90, 0x8e, 0x3f, 0xcf, 0x88, 0xfd,
	0x8c, 0x67, 0x73, 0x26, 0x58, 0x5d, 0x53, 0x70, 0x7a, 0xcd, 0xbf, 0x68, 0x00, 0x6c, 0x3e, 0x98,
	0xec, 0xfa, 0xb1, 0xbf, 0x22, 0xf1, 0xad, 0xbc, 0x28, 0x75, 0x9c, 0x43, 0x71, 0x69, 0x39, 0x75,
	0x59, 0xe8, 0x09, 0x5b, 0x41, 0xda, 0x36, 0x0a, 0xf1, 0x92, 0x24, 0x34, 0x4e, 0x7c, 0x61, 0x2c,
	0x4a, 0xe3, 0x1a, 0xa3, 0xe7, 0x00, 0xfc, 0x29, 0x25, 0x89, 0x78, 0x57, 0xe2, 0x5b, 0xf9, 0xb5,
	0xeb, 0x78, 0x4b, 0xd3, 0xfe, 0xb7, 0x06, 0x2a, 0xf9, 0xad, 0x43, 0x55, 0x50, 0x36, 0x47, 0x03,
	0x3c, 0xb6, 0x07, 0xf0, 0x01, 0x2a, 0x83, 0xa2, 0x3d, 0x9e, 0x42, 0x0d, 0x7d, 0x02, 0xea, 0x17,
	0xf6, 0x68, 0x30, 0xbe, 0x98, 0x3a, 0x93, 0xe1, 0x78, 0x64, 0xc1, 0x02, 0x6a, 0x00, 0x70, 0x7c,
	0x6a, 0xf6, 0xdf, 0x1e, 0x5b, 0x18, 0xff, 0x04, 0x8b, 0x68, 0x1f, 0x54, 0x37, 0xf8, 0x47, 0x58,
	0x12, 0xce, 0xd3, 0xef, 0x0e, 0xe0, 0x9e, 0x14, 0x8e, 0x0e, 0xe0, 0x43, 0x11, 0x65, 0xf2, 0xd3,
	0x6c, 0x38, 0x1e, 0x39, 0xfd, 0x53, 0xdb, 0x1a, 0xcd, 0x60, 0x19, 0xe9, 0x60, 0x6f, 0x66, 0xff,
	0xc1, 0x1a, 0xc1, 0x8a, 0x08, 0x68, 0x8d, 0x66, 0x16, 0x9e, 0x60, 0x7b, 0x6a, 0x41, 0x5d, 0x04,
	0x9c, 0x9c, 0x9a, 0xb3, 0x93, 0x31, 0x3e, 0x73, 0xba, 0x07, 0x10, 0xec, 0x2a, 0xba, 0xb0, 0xda,
	0x7e, 0x05, 0x1a, 0xbb, 0xdf, 0x57, 0xec, 0x1e, 0x5b, 0xa7, 0x96, 0x39, 0xb5, 0xe0, 0x03, 0x54,
	0x01, 0xa5, 0x63, 0x6b, 0x66, 0x42, 0x4d, 0xac, 0x62, 0x9e, 0x4e, 0x86, 0x26, 0x2c, 0x08, 0x71,
	0x60, 0x1d, 0x9f, 0xbf, 0x81, 0xc5, 0xe6, 0xdf, 0xf7, 0x40, 0xf9, 0x62, 0xf3, 0x40, 0xc5, 0x74,
	0xe1, 0x24, 0xec, 0x8a, 0x86, 0x32, 0xf3, 0x3a, 0xae, 0xc4, 0x74, 0x31, 0x13, 0x58, 0x7c, 0x94,
	0xed, 0xda, 0xd3, 0x71, 0x0e, 0x91, 0x05, 0x6a, 0x37, 0x74, 0xee, 0x39, 0x51, 0x76, 0xf1, 0x64,
	0xea, 0xab, 0x1f, 0xb4, 0x23, 0xb5, 0x88, 0xf8, 0xf5, 0x94, 0x0e, 0x57, 0x6f, 0x36, 0xa0, 0xf9,
	0xb7, 0x12, 0xa8, 0x6e, 0x19, 0xd1, 0xf7, 0xe0, 0x49, 0xca, 0x29, 0x77, 0x22, 0x12, 0x27, 0xbe,
	0xeb, 0x47, 0x24, 0x4c, 0x1c, 0x3f, 0x74, 0xae, 0x68, 0x76, 0x2b, 0x2a, 0xf8, 0x53, 0x61, 0x9e,
	0x6c, 0xac, 0x76, 0xf8, 0x96, 0xde, 0xa2, 0xdf, 0x82, 0xa7, 0x3c, 0x8d, 0x22, 0x16, 0x27, 0xdc,
	0xe1, 0x09, 0x89, 0x63, 0xea, 0x39, 0x2b, 0xca, 0x39, 0xb9, 0xa4, 0x5c, 0xee, 0xbc, 0x82, 0x9f,
	0xe4, 0x84, 0x69, 0x66, 0x3f, 0x53, 0x66, 0xf4, 0x3b, 0xd0, 0x5c, 0xfb, 0x7a, 0xcc, 0x4d, 0x57,
	0x62, 0xbe, 0x58, 0x3b, 0x67, 0x13, 0x88, 0x91, 0x33, 0x06, 0x8a, 0xb0, 0xf6, 0xee, 0x81, 0xc7,
	0x6b, 0xef, 0x34, 0x0e, 0x36, 0x8e, 0x25, 0xe9, 0xf8, 0x28, 0x37, 0x9e, 0xc7, 0xc1, 0xda, 0xe7,
	0x00, 0x7c, 0xba, 0xf6, 0x59, 0x51, 0xcf, 0x27, 0x4e, 0x4c, 0x93, 0xf8, 0x56, 0x76, 0x9d, 0x0a,
	0x46, 0xb9, 0xed, 0x4c, 0x98, 0xb0, 0xb0, 0xa0, 0x5f, 0x83, 0xb5, 0xd6, 0xa1, 0x3d, 0xea, 0xf8,
	0x2b, 0x72, 0x49, 0x65, 0x13, 0xaa, 0x60, 0x98, 0x5b, 0xac, 0x1e, 0xb5, 0x85, 0xfe, 0x03, 0xf6,
	0xb5, 0xef, 0x51, 0x26, 0x9b, 0xd2, 0x2e, 0xfb, 0x9d, 0xd0, 0x7f, 0xc0, 0x26, 0xa9, 0xe7, 0x33,
	0xd9, 0xa1, 0x76, 0xd9, 0xa6, 0xd0, 0xef, 0x9c, 0x57, 0xb0, 0xf3, 0x8c, 0xc9, 0x8e, 0xb5, 0x75,
	0x5e, 0xab, 0x47, 0xf3, 0x5c, 0xa1, 0xaf, 0x41, 0x63, 0x9d, 0x58, 0x31, 0xa3, 0x70, 0xd9, 0xbc,
	0x74, 0x5c, 0xcf, 0xb5, 0x62, 0x12, 0xe1, 0xed, 0xa7, 0xf9, 0x90, 0xa8, 0x06, 0x35, 0x71, 0x8d,
	0x47, 0xa2, 0xe4, 0x1e, 0xb4, 0xff, 0xa9, 0x81, 0xea, 0xd6, 0x08, 0x23, 0x6e, 0xfb, 0xf9, 0xe8,
	0xed, 0x68, 0x7c, 0x31, 0xca, 0x6e, 0xfb, 0x85, 0x7d, 0x62, 0x43, 0x4d, 0x48, 0xd6, 0xe0, 0x8d,
	0x05, 0x3d, 0x21, 0xd9, 0x03, 0x6b, 0x04, 0x65, 0x90, 0xf3, 0xb3, 0xd9, 0x14, 0x2e, 0xa4, 0xf5,
	0xdd, 0x60, 0x0c, 0x2f, 0x85, 0xf4, 0x66, 0x82, 0xa7, 0x70, 0x29, 0x8a, 0x62, 0x38, 0x1d, 0x4c,
	0x4c, 0xe8, 0x67, 0xe2, 0xf9, 0xc4, 0x84, 0x3f, 0x0b, 0xfb, 0x70, 0x3a, 0x31, 0xe1, 0x95, 0x90,
	0xfa, 0x83, 0x33, 0x13, 0xca, 0x02, 0x1b, 0x8f, 0xac, 0xf7, 0x78, 0x36, 0x83, 0x2b, 0xc1, 0xb5,
	0x86, 0x78, 0x32, 0x80, 0xa1, 0xa8, 0xf1, 0xd3, 0x99, 0x05, 0x59, 0xe6, 0x3f, 0x31, 0x27, 0x30,
	0x6a, 0xbb, 0xa0, 0xbe, 0x33, 0x2f, 0x89, 0x27, 0x12, 0x5b, 0xe6, 0x74, 0x3c, 0xca, 0x1f, 0x53,
	0x85, 0xd4, 0x63, 0xaa, 0x90, 0x7a, 0x4c, 0x15, 0x3a, 0x84, 0xc5, 0x2d, 0xf4, 0x1d, 0x2c, 0x6d,
	0xa1, 0xef, 0xe1, 0xc3, 0x76, 0x0f, 0xec, 0xdf, 0x99, 0x53, 0xe4, 0xb6, 0x7e, 0x9c, 0xc9, 0x35,
	0x94, 0xd8, 0xcd, 0x7a, 0x80, 0x10, 0x7b, 0xb0, 0xd0, 0xfe, 0x6f, 0x11, 0xc0, 0x61, 0x3e, 0x9c,
	0xab, 0xfb, 0x88, 0x5e, 0x83, 0x9a, 0x9a, 0xaa, 0x97, 0x34, 0x08, 0x98, 0x7a, 0x65, 0xbf, 0x78,
	0x71, 0x97, 0xa8, 0x6a, 0x7b, 0x28, 0x48, 0xb8, 0xea, 0x6e, 0x80, 0x88, 0xc0, 0x69, 0x7c, 0x4d,
	0x63, 0x15, 0xa1, 0x78, 0x5f, 0x84, 0xa9, 0x64, 0xa9, 0x08, 0x7c, 0x03, 0x50, 0x1f, 0xd4, 0xf3,
	0xc9, 0xde, 0x0f, 0x7d, 0xbe, 0x94, 0xe5, 0x53, 0xed, 0x3d, 0xbf, 0x6f, 0x13, 0x27, 0x92, 0x85,
	0xd5, 0xc6, 0x33, 0xd4, 0xfc, 0x23, 0xa8, 0x6e, 0x6d, 0x51, 0xbc, 0x1b, 0x34, 0x5a, 0xd2, 0x15,
	0x8d, 0x49, 0x20, 0xbb, 0x47, 0x0d, 0x6f, 0x14, 0x72, 0x66, 0x4d, 0x48, 0xe2, 0xbb, 0xf2, 0xbc,
	0x35, 0xac, 0x50, 0xf6, 0xef, 0x63, 0xd3, 0xd3, 0x6a, 0x38, 0x87, 0x22, 0xfc, 0xd6, 0xfe, 0xff,
	0xef, 0xe1, 0x5f, 0x83, 0xda, 0xf6, 0xd9, 0xb6, 0x22, 0x68, 0xf7, 0x45, 0x28, 0xec, 0x44, 0x68,
	0xff, 0x47, 0x03, 0x70, 0x24, 0xfe, 0x88, 0xf5, 0xc5, 0x03, 0xb8, 0xf0, 0x5d, 0x92, 0xc8, 0x7f,
	0x53, 0x1e, 0x4d, 0x88, 0x1f, 0x70, 0x15, 0x27, 0x87, 0xf2, 0x5d, 0xf5, 0x2f, 0x43, 0x59, 0x6b,
	0x2a, 0xd4, 0x46, 0xd1, 0xfc, 0x33, 0x28, 0x0f, 0x14, 0x51, 0xec, 0x84, 0xc6, 0xbe, 0x3a, 0x66,
	0x1d, 0x2b, 0x24, 0xf4, 0x3e, 0xe7, 0x29, 0x8d, 0xd5, 0xe3, 0xa0, 0x90, 0x58, 0x92, 0xbe, 0x8f,
	0xfc, 0x58, 0xb5, 0xcf, 0x12, 0xce, 0xa1, 0xb0, 0xf0, 0x74, 0xfe, 0xb3, 0xf8, 0x2f, 0x93, 0xcd,
	0x5e, 0x39, 0x14, 0x13, 0x99, 0x68, 0xf2, 0x7b, 0x72, 0x1b, 0x42, 0xfc, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa6, 0xe2, 0xdf, 0xb0, 0x5d, 0x0e, 0x00, 0x00,
}
